#!/bin/bash
docker run -d --restart=always --network plex --ip 10.0.17.97 --name=jellyfin -e PGID=666 -e PUID=666 -v /aws:/aws -v /home/docker/jellyfin/config:/config -v /home/docker/jellyfin/cache:/cache jellyfin/jellyfin 
