#!/bin/bash
docker run -d --restart=always --name=pandora -e PUID=666 -e PGID=666 -v /home/docker/pandora/config:/config -v /home/docker/pandora/data:/data -v /aws:/aws -v /cloud:/cloud -v /:/host:ro -e VIRTUAL_HOST=cloud.pknw1plex.co.uk -e VIRTUAL_PORT=443 -p 555:443 linuxserver/pandora
