#!/bin/bash

if [[ $(docker ps -a -f name=pihole|grep -v CREAT) ]]
then
	echo "existing container - remove and re-check"
	docker rm -f pihole
	exec /home/docker/scripts/pihole 
else
	docker run -d --restart=always --name=pihole -e VIRTUAL_HOST=pihole -e HOST_GID=666 -e HOST_UID=666 -e ServerIP="10.0.17.53" --network plex --ip 10.0.17.53 --dns 8.8.8.8 --cap-add=NET_ADMIN -v /home/docker/pihole/etc:/etc/pihole -v /home/docker/pihole/dnsmasq.d:/etc/dnsmasq.d diginc/pi-hole
	exit 0
fi
